"""Tests for GapAnalysisService._normalize_reduce_output."""

from __future__ import annotations

import copy

import pytest

from legal_portal.services.analysis.gap_analysis_service import GapAnalysisService


@pytest.fixture()
def service():
    """Create a GapAnalysisService with no dependencies for unit testing."""
    # The normalizer is a pure method; we only need the instance for method access.
    svc = object.__new__(GapAnalysisService)
    return svc


def _base_item(**overrides) -> dict:
    """Return a minimal valid GapItem dict, with optional overrides."""
    item = {
        "gap_id": "gap_1",
        "category": "missing_document",
        "severity": "high",
        "title": "Missing contract",
        "description": "The signed contract is absent from the file.",
        "impact_on_case": "Cannot verify agreement terms.",
        "affected_issue": "Breach of contract",
        "related_documents": ["doc1.pdf"],
        "recommendations": ["Request signed copy"],
    }
    item.update(overrides)
    return item


def _wrap(category: str, items: list[dict]) -> dict:
    """Wrap items into a minimal GapAnalysisResult-shaped dict."""
    return {
        "total_gaps": len(items),
        "critical_count": 0,
        "high_count": 0,
        "medium_count": 0,
        "low_count": 0,
        "gaps_by_category": {category: items},
        "overall_completeness_score": 75.0,
        "attorney_summary": "Test summary.",
    }


# ── 1. Freeform category keys mapped to enum values ──


def test_freeform_category_key_mapped(service):
    data = _wrap("payment proof", [_base_item()])
    result = service._normalize_reduce_output(data)
    assert "missing_document" in result["gaps_by_category"]
    assert "payment proof" not in result["gaps_by_category"]


# ── 2. Multiple freeform keys mapped to same enum get merged ──


def test_duplicate_categories_merged(service):
    data = {
        **_wrap("missing docs", [_base_item(gap_id="g1")]),
    }
    data["gaps_by_category"]["absent records"] = [_base_item(gap_id="g2")]
    result = service._normalize_reduce_output(data)
    items = result["gaps_by_category"]["missing_document"]
    assert len(items) == 2


# ── 3. Missing gap_id auto-generated ──


def test_missing_gap_id_autogenerated(service):
    item = _base_item()
    del item["gap_id"]
    data = _wrap("missing_document", [item])
    result = service._normalize_reduce_output(data)
    gap = result["gaps_by_category"]["missing_document"][0]
    assert gap["gap_id"].startswith("gap_reduce_")


# ── 4. Missing impact_on_case filled from description ──


def test_missing_impact_filled_from_description(service):
    item = _base_item()
    del item["impact_on_case"]
    data = _wrap("missing_document", [item])
    result = service._normalize_reduce_output(data)
    gap = result["gaps_by_category"]["missing_document"][0]
    assert gap["impact_on_case"] == item["description"]


# ── 5. Field name remapping ──


def test_field_name_remapping(service):
    item = _base_item()
    # Replace correct fields with wrong LLM field names
    del item["affected_issue"]
    del item["recommendations"]
    del item["related_documents"]
    item["affected_issues"] = ["Breach of contract", "Damages"]
    item["suggested_action"] = "Request the signed contract"
    item["supporting_documents"] = ["doc1.pdf", "doc2.pdf"]

    data = _wrap("missing_document", [item])
    result = service._normalize_reduce_output(data)
    gap = result["gaps_by_category"]["missing_document"][0]

    assert gap["affected_issue"] == "Breach of contract"
    assert gap["recommendations"] == ["Request the signed contract"]
    assert gap["related_documents"] == ["doc1.pdf", "doc2.pdf"]
    assert "affected_issues" not in gap
    assert "suggested_action" not in gap
    assert "supporting_documents" not in gap


# ── 6. Already-valid data passes through unchanged ──


def test_valid_data_passthrough(service):
    item = _base_item()
    data = _wrap("missing_document", [item])
    data["reconciliation_notes"] = ["Note 1"]
    original = copy.deepcopy(data)

    result = service._normalize_reduce_output(data)

    # Core content unchanged (counts recalculated but should match)
    gap = result["gaps_by_category"]["missing_document"][0]
    assert gap["title"] == original["gaps_by_category"]["missing_document"][0]["title"]
    assert gap["description"] == original["gaps_by_category"]["missing_document"][0]["description"]
    assert result["reconciliation_notes"] == ["Note 1"]


# ── 7. Missing reconciliation_notes added as [] ──


def test_missing_reconciliation_notes_defaults(service):
    data = _wrap("missing_document", [_base_item()])
    assert "reconciliation_notes" not in data
    result = service._normalize_reduce_output(data)
    assert result["reconciliation_notes"] == []


# ── 8. Severity counts recalculated from actual items ──


def test_severity_counts_recalculated(service):
    items = [
        _base_item(gap_id="g1", severity="critical"),
        _base_item(gap_id="g2", severity="high"),
        _base_item(gap_id="g3", severity="high"),
        _base_item(gap_id="g4", severity="low"),
    ]
    data = _wrap("missing_document", items)
    # Set wrong counts
    data["critical_count"] = 99
    data["high_count"] = 99

    result = service._normalize_reduce_output(data)
    assert result["critical_count"] == 1
    assert result["high_count"] == 2
    assert result["medium_count"] == 0
    assert result["low_count"] == 1
    assert result["total_gaps"] == 4


# ── 9. Unknown category key falls back to incomplete_info ──


def test_unknown_category_falls_back(service):
    data = _wrap("something_totally_unknown_xyz", [_base_item()])
    result = service._normalize_reduce_output(data)
    assert "incomplete_info" in result["gaps_by_category"]
    assert "something_totally_unknown_xyz" not in result["gaps_by_category"]
