from __future__ import annotations

import re
from unittest.mock import MagicMock

import pytest

from backend.utils.data_models import (
    AnalyzedDocument,
    CaseAnalysisResult,
    DemandLetterEvaluation,
    EnhancedIntakeAnalysis,
    LegalAssessment,
)
from backend_logic.email_generator import EmailGenerator


@pytest.fixture
def mock_openai_client():
    """
    Returns a mock OpenAI client that always returns a canned, style-specific response.
    """

    class MockChatCompletions:
        def create(self, model, messages, **kwargs):
            # Determine which section is being generated by the prompt
            prompt = messages[-1]["content"]
            # Simulate HTML output with lists for factual summary, legal analysis, and next steps
            if "factual summary" in prompt.lower():
                return MagicMock(
                    choices=[
                        MagicMock(
                            message=MagicMock(
                                content="<ul><li>LLW Construction, Inc. contracted for <strong>$128,355.77</strong> to repair 3414 South Belcher Drive, Tampa, FL 33629.</li><li><strong>$100,000</strong> already paid, project not completed.</li><li>Work performed is <strong>substandard</strong>, including improper bathroom framing.</li><li>Contractor requests more money despite minimal progress.</li><li>Received <strong>Notice to Owner</strong> from subcontractor for over <strong>$3,000</strong> unpaid.</li></ul>"
                            )
                        )
                    ]
                )
            if "legal analysis" in prompt.lower():
                return MagicMock(
                    choices=[
                        MagicMock(
                            message=MagicMock(
                                content="<ul><li>Implied warranty breach under <strong>Fla. Stat. Chapter 558</strong></li><li>Construction defects and breach of contract</li><li>Lien/Notice to Owner issues</li></ul>"
                            )
                        )
                    ]
                )
            if "recommended next steps" in prompt.lower():
                return MagicMock(
                    choices=[
                        MagicMock(
                            message=MagicMock(
                                content="<ul><li>Issue demand letter to contractor</li><li>Provide 60-day written notice under <strong>Fla. Stat. Chapter 558</strong></li><li>Pay subcontractor to avoid lien, seek reimbursement</li></ul>"
                            )
                        )
                    ]
                )
            if "executive summary" in prompt.lower():
                return MagicMock(
                    choices=[
                        MagicMock(
                            message=MagicMock(
                                content="<p>Good afternoon Mr. Devlin and Ms. Bell,</p><p>I have completed my review of your legal matter and am prepared to present my findings and recommendations.</p>"
                            )
                        )
                    ]
                )
            # Closing section: return gold standard closing
            if "sincerely" in prompt.lower() or "closing" in prompt.lower():
                return MagicMock(
                    choices=[
                        MagicMock(
                            message=MagicMock(
                                content="<p>Thank you, and we remain committed to protecting your interests throughout this process.</p>"
                            )
                        )
                    ]
                )
            # Default: generic professional, non-collaborative
            return MagicMock(
                choices=[
                    MagicMock(
                        message=MagicMock(
                            content="<p>Direct, professional content. No collaborative language.</p>"
                        )
                    )
                ]
            )

    class MockChat:
        completions = MockChatCompletions()

    class MockOpenAI:
        chat = MockChat()

    return MockOpenAI()


def make_case_analysis(style_marker):
    """
    Returns a CaseAnalysisResult with mock data for the given style marker.
    """
    return CaseAnalysisResult(
        intake_analysis=EnhancedIntakeAnalysis(
            client_name="Client",
            attorney_name="Attorney",
            case_summary="Summary for testing.",
            case_type="Test Case",
            urgency_level="Standard",
            client_priorities=["Priority 1"],
            desired_outcomes=["Outcome 1"],
            key_facts=["Fact 1"],
            parties_involved=[{"name": "Client", "role": "Plaintiff"}],
            financial_impact="10000",
            legal_claims=["Breach of contract"],
        ),
        analyzed_documents=[
            AnalyzedDocument(
                filename="test.pdf",
                document_type="Contract",
                inferred_title="Test Contract",
                summary="Summary of contract.",
                key_information="Key info.",
                relevance_to_case="Relevant because...",
            )
        ],
        legal_assessment=LegalAssessment(
            case_type="Contract",
            claim_viability="Strong",
            overall_evidence_strength="Strong",
            potential_challenges=[],
            recommended_actions=["Action 1"],
            demand_letter_appropriate=True,
            urgency_assessment="Standard",
        ),
        demand_letter_evaluation=DemandLetterEvaluation(
            is_appropriate=True,
            reasoning="Meets requirements.",
            potential_outcomes=["Settlement"],
            relevant_statutes=["Florida Statutes § 95.11"],
        ),
    )


# Legacy style tests removed: Only the gold standard orchestrator test remains.
def test_orchestrated_devlin_style_output(tmp_path, mock_openai_client):
    """
    Gold standard test: Validate that generate_findings_orchestrated produces output matching the Erik Devlin style.
    """
    from backend.tests.utils.email_comparator import EmailComparator

    # Construct a realistic Devlin CaseAnalysisResult
    from backend.utils.data_models import (
        AnalyzedDocument,
        CaseAnalysisResult,
        DemandLetterEvaluation,
        EnhancedIntakeAnalysis,
        LegalAssessment,
    )

    devlin_analysis = CaseAnalysisResult(
        intake_analysis=EnhancedIntakeAnalysis(
            client_name="Amber Bell & Erik Devlin",
            attorney_name="Erik Devlin",
            case_summary="Dispute with LLW Construction, Inc. regarding incomplete and substandard repairs after Hurricane Helene.",
            case_type="Contractor Dispute",
            urgency_level="Standard",
            client_priorities=["Complete repairs", "Recover losses"],
            desired_outcomes=["Project completion", "Financial reimbursement"],
            key_facts=[
                "LLW Construction, Inc. contracted for $128,355.77 to repair 3414 South Belcher Drive, Tampa, FL 33629.",
                "$100,000 already paid, project not completed.",
                "Work performed is substandard, including improper bathroom framing.",
                "Contractor requests more money despite minimal progress.",
                "Received Notice to Owner from subcontractor for over $3,000 unpaid.",
            ],
            parties_involved=[
                {"name": "Amber Bell", "role": "Homeowner"},
                {"name": "Erik Devlin", "role": "Homeowner"},
                {"name": "LLW Construction, Inc.", "role": "Contractor"},
            ],
            financial_impact="$128,355.77 contract, $100,000 paid, $3,000+ unpaid to subcontractor",
            legal_claims=[
                "Implied warranty breach",
                "Construction defects",
                "Breach of contract",
                "Lien/Notice to Owner issues",
            ],
        ),
        analyzed_documents=[
            AnalyzedDocument(
                filename="Devlin - Contract for Construction - Highlighted w Items not Completed 6.9.25.pdf",
                document_type="Contract",
                inferred_title="Construction Contract",
                summary="Contract for repairs after hurricane damage.",
                key_information="Contractor failed to complete work as agreed.",
                relevance_to_case="Central to breach of contract claim.",
            )
        ],
        legal_assessment=LegalAssessment(
            case_type="Contractor Dispute",
            claim_viability="Strong",
            overall_evidence_strength="Strong",
            potential_challenges=["Contractor out of funds", "Subcontractor liens"],
            recommended_actions=[
                "Issue demand letter to contractor",
                "Provide 60-day written notice under Fla. Stat. Chapter 558",
                "Pay subcontractor to avoid lien, seek reimbursement",
            ],
            demand_letter_appropriate=True,
            urgency_assessment="Standard",
        ),
        demand_letter_evaluation=DemandLetterEvaluation(
            is_appropriate=True,
            reasoning="Contractor failed to perform, demand letter required.",
            potential_outcomes=["Project completion", "Reimbursement", "Litigation"],
            relevant_statutes=["Fla. Stat. Chapter 558", "Fla. Stat. Chapter 713"],
        ),
    )

    # Generate the findings letter using the orchestrator
    generator = EmailGenerator(client=mock_openai_client)
    letter = generator.generate_findings_orchestrated(devlin_analysis)
    generated_html = letter.executive_summary

    # Load and process the gold standard RTF
    reference_rtf_path = (
        "backend/tests/test_results/devlin/reference/reference_email.rtf"
    )
    comparator = EmailComparator(reference_rtf_path, generated_html)
    comparison_results, generated_text = comparator.compare()

    # 1. Assert subject line present and correct
    assert (
        "Subject:" in generated_text
        and "Legal Review and Recommended Next Steps" in generated_text
    ), "Subject line missing or incorrect."

    # 2. Assert correct greeting
    assert "Good afternoon Mr. Devlin and Ms. Bell" in generated_text, (
        "Greeting does not match gold standard."
    )

    # 3. Assert structure: Intro -> Body -> Closing
    assert (
        "FACTUAL SUMMARY" in generated_text
        and "RECOMMENDED NEXT STEPS" in generated_text
    ), "Required sections missing."

    # 4. Assert all section headers are numbered and ALL CAPS

    headers = re.findall(r"\d+\.\s+[A-Z ]+", generated_text)
    assert headers, "No numbered ALL CAPS section headers found."
    for h in headers:
        assert h == h.upper(), f"Section header not ALL CAPS: {h}"

    # 5. Assert formatting: <ul>, <li>, <strong>
    assert "<ul>" in generated_html and "<li>" in generated_html, (
        "Bulleted list formatting missing."
    )
    assert "<strong>" in generated_html, "Emphasis formatting (<strong>) missing."

    # 6. Assert no repeated greetings or closings
    greetings = re.findall(r"Good afternoon", generated_text)
    closings = re.findall(r"Thank you, and we remain committed", generated_text)
    assert len(greetings) == 1, "Repeated greeting found."
    assert len(closings) == 1, "Repeated closing found."

    # 7. Assert professional closing present
    assert "Thank you, and we remain committed" in generated_text, (
        "Professional closing missing."
    )

    # 8. Manual inspection for tone (print output for review)
    print("\n--- GENERATED EMAIL OUTPUT (for manual tone inspection) ---\n")
    print(generated_text)
    print("\n--- END GENERATED EMAIL OUTPUT ---\n")

    # 9. Assert semantic similarity is high (substance)
    substance_score = comparison_results.get("substance", {}).get("score", 0)
    assert substance_score > 0.85, f"Semantic similarity too low: {substance_score}"

    # 10. Structure similarity is not asserted because all content is in executive_summary by design.

    # 11. Assert tone score is high
    tone_score = comparison_results.get("tone", {}).get("score", 0)
    assert tone_score > 0.7, f"Tone similarity too low: {tone_score}"

    # If any assertion fails, pytest will report and print the mismatched output.
