cookie:
  expiry_days: 30
  key: -N8AGMikvN1huMz-QRdnqKR4RV2ecBo8YioSdOKtKrM
  name: legal_portal_auth
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrator
      password: $2b$12$SbjvZPnZcoM2Uf.sMHB42ecNKqdN2eNJYrHROu9/tlSkpimnIgowK
      role: admin
jwt_secret: n_2dNu84pgvEHQhBy99pF4Mfh4EY2TiJre3XZMbIgXk
preauthorized:
  emails: []
